### ISSUE TITLE
windows miner seems to be version 0.0.3 still

### ISSUE THREAD

**Issue by lw2020** [Evanesco-Labs/miner#18]
\miner-windows\miner-windows2>miner.exe -v
miner.exe version v0.0.3

INFO [09-07|09:41:12.994] start new mining epoch
INFO [09-07|09:41:12.995] vrf finished                             challenge height:=87039 index:=39
INFO [09-07|09:41:12.995] waiting for challenge block              time duration (second)=234

**Comment by calehh** [comment]
Thanks, we have updated [miner-windows.zip](https://github.com/Evanesco-Labs/miner/releases/download/v0.0.4/miner-windows.zip).
